/** Common company name → domain hints for parsing user messages (not routing). */
export const KNOWN_COMPANY_DOMAINS: Record<string, string> = {
  amazon: "amazon.com",
  stripe: "stripe.com",
  google: "google.com",
  alphabet: "google.com",
  apple: "apple.com",
  microsoft: "microsoft.com",
  meta: "meta.com",
  facebook: "meta.com",
  netflix: "netflix.com",
  tesla: "tesla.com",
  nvidia: "nvidia.com",
  salesforce: "salesforce.com",
  shopify: "shopify.com",
  uber: "uber.com",
  airbnb: "airbnb.com",
  openai: "openai.com",
  anthropic: "anthropic.com",
  notion: "notion.so",
  figma: "figma.com",
  linear: "linear.app",
  slack: "slack.com",
  datadog: "datadoghq.com",
  snowflake: "snowflake.com",
};
